ALTER TABLE "effects" ADD COLUMN "effects" text;--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "tingly";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "cancer";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "pms";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "spinal_cord_injury";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "pain";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "relaxed";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "aroused";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "muscle_spasms";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "depression";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "migraines";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "paranoid";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "inflammation";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "phantom_limb_pain";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "talkative";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "dry_eyes";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "dry_mouth";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "stress";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "alzheimers";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "eye_pressure";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "ptsd";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "fibromyalgia";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "anxious";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "dizzy";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "add_adh";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "epilepsy";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "anorexia";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "multiple_sclerosis";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "headaches";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "sleepy";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "fatigue";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "hiv_aids";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "nausea";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "euphoric";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "asthma";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "energetic";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "giggly";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "tourettes_syndrome";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "gastrointestinal_disorder";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "spasticity";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "anxiety";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "uplifted";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "cramps";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "parkinsons";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "hypertension";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "glaucoma";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "crohns_disease";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "insomnia";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "focused";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "hungry";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "muscle_dystrophy";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "creative";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "happy";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "lack_of_appetite";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "seizures";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "bipolar_disorder";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "tinnitus";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "arthritis";--> statement-breakpoint
ALTER TABLE "effects" DROP COLUMN "headache";